-- 042_seed_honeybook_templates.sql
-- Seeds 13 email templates + 4 questionnaire forms (proofread/adapted
-- from the HoneyBook library). Idempotent: every INSERT is guarded with
-- WHERE NOT EXISTS, so re-running is a no-op. Generated by gen_seed.py.

-- ── Email templates ──────────────────────────────────────────────
INSERT INTO email_templates (name, subject, body)
SELECT 'Booking confirmation + next steps', 'You''re booked! Here''s what happens next', 'Hi {client_name},

I''m looking forward to working together. Now that your [service name] is booked, here''s what happens next:

Before our session, please take a moment to fill out this short intake form: [intake form link]. It gives me helpful insight into your business and what you''re looking for.

If any questions come up before we shoot, just reply here — I''m happy to help.

Thank you!
{site_name}'
WHERE NOT EXISTS (SELECT 1 FROM email_templates WHERE name='Booking confirmation + next steps' AND deleted_at IS NULL);
INSERT INTO email_templates (name, subject, body)
SELECT 'Reply: request for lower price', 'Re: Pricing', 'Hi {first_name},

Thanks so much for your interest in working together. My pricing reflects the time, quality, and care that go into every project, and at this point I''m not able to offer discounts on my rates.

I''d still love to find a way to work together. If the budget doesn''t quite line up, let me know — I''m happy to recommend another photographer who may be a better fit for your needs.

Best,
{site_name}'
WHERE NOT EXISTS (SELECT 1 FROM email_templates WHERE name='Reply: request for lower price' AND deleted_at IS NULL);
INSERT INTO email_templates (name, subject, body)
SELECT 'Client satisfaction survey', 'How did we do?', 'Hi {first_name},

I really enjoyed working with you, and I wanted to follow up to make sure your experience was a great one from start to finish.

Your feedback helps me see what''s working and where I can improve. If you have a few minutes, would you mind sharing your thoughts? It only takes a moment: [feedback survey link]

Thanks so much for your time.

Best,
{site_name}'
WHERE NOT EXISTS (SELECT 1 FROM email_templates WHERE name='Client satisfaction survey' AND deleted_at IS NULL);
INSERT INTO email_templates (name, subject, body)
SELECT 'Reply to inquiry — with brochure', 'Thank you for your inquiry!', 'Hi {first_name},

Thank you for reaching out! I''d love to learn more about your project, and I''m excited about the possibility of working together.

I''ve attached my brochure so you can get a feel for my services and pricing. If you don''t see exactly what you''re looking for, no problem — I''m happy to tailor something to your needs.

When you have a moment, take a look and let me know which services you''d like to explore: [brochure / services link]. Once you''ve made a selection, I''ll reach out to get things started.

In the meantime, please don''t hesitate to send over any questions.

Best,
{site_name}'
WHERE NOT EXISTS (SELECT 1 FROM email_templates WHERE name='Reply to inquiry — with brochure' AND deleted_at IS NULL);
INSERT INTO email_templates (name, subject, body)
SELECT 'Reply: request for a discount (warm)', 'Re: Pricing', 'Hi {first_name},

Thank you so much for your interest — I''m grateful our paths have crossed, and genuinely excited about what you''re planning!

Talking about budget can be a tricky conversation to navigate, and I completely understand. At this point my business has grown to where I''m not able to offer discounted pricing. I''ve adjusted my rates over the years to keep up with demand while making sure every client gets a custom, high-quality experience worth every penny.

I would absolutely love the chance to work with you. If the budget doesn''t allow for it right now, I''m more than happy to point you toward another professional who might be a great fit — just say the word and I''ll share a few recommendations.

Thank you again,
{site_name}'
WHERE NOT EXISTS (SELECT 1 FROM email_templates WHERE name='Reply: request for a discount (warm)' AND deleted_at IS NULL);
INSERT INTO email_templates (name, subject, body)
SELECT 'Gallery delivery — sharing & credit', 'Your gallery is ready!', 'Hi {first_name},

I''m so excited to share that your gallery is ready to view and download! It was a joy hand-picking, fine-tuning, and editing each image, and I hope you love them as much as I do: [gallery link]

I love it when clients share their photos — it''s a wonderful way to let others in on what we created together. You''re more than welcome to post the images anywhere you like. I only ask one small favor: please credit my work, and avoid adding filters or extra edits on top of the photos.

Referrals and tags are one of my main sources of new work, so a quick credit genuinely means the world. To credit me, just tag [your Instagram handle] or mention {site_name} in your caption. It seems like a small thing, but it makes a big difference!

If you have any questions at all, let me know. I can''t wait to see how you use them!

You''re the best,
{site_name}'
WHERE NOT EXISTS (SELECT 1 FROM email_templates WHERE name='Gallery delivery — sharing & credit' AND deleted_at IS NULL);
INSERT INTO email_templates (name, subject, body)
SELECT 'Request for a testimonial', 'A quick favor?', 'Hi {first_name},

Can you believe it''s already been a month since we worked together? Time is flying! I''ve been thinking back to [personal detail from the project].

I wanted to check in, see how you''re doing, and ask whether there''s anything else I can help you with. I''d also love to hear about your experience working with me — what you enjoyed most, and anything I could do better.

If you''re comfortable, would you be willing to spend five minutes sharing a few thoughts? [review link] Reviews are one of the best ways for me to keep every client leaving as a raving fan, and your feedback would mean a lot.

Thank you again for choosing me!

Best,
{site_name}'
WHERE NOT EXISTS (SELECT 1 FROM email_templates WHERE name='Request for a testimonial' AND deleted_at IS NULL);
INSERT INTO email_templates (name, subject, body)
SELECT 'Follow-up: questionnaire (3-day)', 'Just checking in', 'Hi {first_name},

I hope this finds you well!

I wanted to follow up on the questionnaire I sent over to get things started. You can fill it out here whenever you have a moment: [questionnaire link]

I''d love to find a time to talk through the details soon. Are you free this week? Once you''ve submitted the questionnaire, you can grab a slot that works for you here: [scheduling link]

Looking forward to it!
{site_name}'
WHERE NOT EXISTS (SELECT 1 FROM email_templates WHERE name='Follow-up: questionnaire (3-day)' AND deleted_at IS NULL);
INSERT INTO email_templates (name, subject, body)
SELECT 'Reply to inquiry — with questionnaire', 'Thanks for reaching out — a few quick questions', 'Hi {first_name},

Thank you for your interest! I''d love to learn a bit more about your project, and I''m excited about the possibility of working together.

Below you''ll find a short questionnaire with a few questions to help me understand what you need. If you''re unsure about anything, no worries — we can fine-tune the details later: [questionnaire link]

Once you''ve submitted your answers, I''ll follow up with next steps.

Thanks in advance — I look forward to hearing from you!

Best,
{site_name}'
WHERE NOT EXISTS (SELECT 1 FROM email_templates WHERE name='Reply to inquiry — with questionnaire' AND deleted_at IS NULL);
INSERT INTO email_templates (name, subject, body)
SELECT 'Follow-up: any questions? (3-day)', 'Any questions?', 'Hi {first_name},

I hope you''re having a great day. I wanted to follow up and see whether you had any questions about what I sent over. You can find it here: [document link]

Feel free to reach out anytime — I look forward to hearing from you!

Best,
{site_name}'
WHERE NOT EXISTS (SELECT 1 FROM email_templates WHERE name='Follow-up: any questions? (3-day)' AND deleted_at IS NULL);
INSERT INTO email_templates (name, subject, body)
SELECT 'Reply to inquiry (default)', 'Thank you for reaching out', 'Hi {first_name},

Thanks for your interest in working together! I''d love to learn a bit more about your project, and I''m excited about the possibility of collaborating.

If there''s anything we didn''t capture from your inquiry, please feel free to send along any extra details or questions.

Thanks again for reaching out — I''ll be in touch shortly.

Best,
{site_name}'
WHERE NOT EXISTS (SELECT 1 FROM email_templates WHERE name='Reply to inquiry (default)' AND deleted_at IS NULL);
INSERT INTO email_templates (name, subject, body)
SELECT 'Thank you (default)', 'Thank you for reaching out', 'Hi {first_name},

Thanks so much for reaching out!

I''d love to hear more about what you have in mind and how we might work together. Looking forward to learning all about it.

I''ll be in touch soon!
{site_name}'
WHERE NOT EXISTS (SELECT 1 FROM email_templates WHERE name='Thank you (default)' AND deleted_at IS NULL);
INSERT INTO email_templates (name, subject, body)
SELECT 'Proposal email (default)', 'Your customized proposal', 'Hi {first_name},

I''ve put together a customized proposal for you to review: {doc_url}

Once you open it, you''ll be able to review the proposed services, sign the contract, and make a payment online — all in one place.

Let me know if you have any questions. Excited to work together!

Best,
{site_name}'
WHERE NOT EXISTS (SELECT 1 FROM email_templates WHERE name='Proposal email (default)' AND deleted_at IS NULL);

-- ── Questionnaire forms + fields ─────────────────────────────────
INSERT INTO forms (slug, title, kind, intro, active)
SELECT 'ciSvxgKPQVoaIF', 'Pre-Wedding Photography Questionnaire', 'questionnaire', 'Filling out this questionnaire is one of the most important steps in planning your wedding photography. It helps me capture the details, groups, and moments that matter most to you. Please answer in as much detail as you can — more is always better than less.', 1
WHERE NOT EXISTS (SELECT 1 FROM forms WHERE title='Pre-Wedding Photography Questionnaire');
INSERT INTO form_fields (form_id, label, ftype, required, options, sort_order)
SELECT f.id, 'You and your partner''s full names', 'short_text', 1, NULL, 1
FROM forms f WHERE f.slug='ciSvxgKPQVoaIF'
  AND NOT EXISTS (SELECT 1 FROM form_fields ff WHERE ff.form_id=f.id AND ff.label='You and your partner''s full names');
INSERT INTO form_fields (form_id, label, ftype, required, options, sort_order)
SELECT f.id, 'Wedding date', 'date', 1, NULL, 2
FROM forms f WHERE f.slug='ciSvxgKPQVoaIF'
  AND NOT EXISTS (SELECT 1 FROM form_fields ff WHERE ff.form_id=f.id AND ff.label='Wedding date');
INSERT INTO form_fields (form_id, label, ftype, required, options, sort_order)
SELECT f.id, 'Best email(s) to reach you', 'email', 1, NULL, 3
FROM forms f WHERE f.slug='ciSvxgKPQVoaIF'
  AND NOT EXISTS (SELECT 1 FROM form_fields ff WHERE ff.form_id=f.id AND ff.label='Best email(s) to reach you');
INSERT INTO form_fields (form_id, label, ftype, required, options, sort_order)
SELECT f.id, 'Best phone number(s)', 'short_text', 0, NULL, 4
FROM forms f WHERE f.slug='ciSvxgKPQVoaIF'
  AND NOT EXISTS (SELECT 1 FROM form_fields ff WHERE ff.form_id=f.id AND ff.label='Best phone number(s)');
INSERT INTO form_fields (form_id, label, ftype, required, options, sort_order)
SELECT f.id, 'Preferred contact method', 'dropdown', 0, '["Email", "Phone call", "Text"]', 5
FROM forms f WHERE f.slug='ciSvxgKPQVoaIF'
  AND NOT EXISTS (SELECT 1 FROM form_fields ff WHERE ff.form_id=f.id AND ff.label='Preferred contact method');
INSERT INTO form_fields (form_id, label, ftype, required, options, sort_order)
SELECT f.id, 'Wedding-day point of contact (name + role, e.g. coordinator)', 'short_text', 0, NULL, 6
FROM forms f WHERE f.slug='ciSvxgKPQVoaIF'
  AND NOT EXISTS (SELECT 1 FROM form_fields ff WHERE ff.form_id=f.id AND ff.label='Wedding-day point of contact (name + role, e.g. coordinator)');
INSERT INTO form_fields (form_id, label, ftype, required, options, sort_order)
SELECT f.id, 'Ceremony location name', 'short_text', 0, NULL, 7
FROM forms f WHERE f.slug='ciSvxgKPQVoaIF'
  AND NOT EXISTS (SELECT 1 FROM form_fields ff WHERE ff.form_id=f.id AND ff.label='Ceremony location name');
INSERT INTO form_fields (form_id, label, ftype, required, options, sort_order)
SELECT f.id, 'Ceremony address', 'short_text', 0, NULL, 8
FROM forms f WHERE f.slug='ciSvxgKPQVoaIF'
  AND NOT EXISTS (SELECT 1 FROM form_fields ff WHERE ff.form_id=f.id AND ff.label='Ceremony address');
INSERT INTO form_fields (form_id, label, ftype, required, options, sort_order)
SELECT f.id, 'Ceremony start time', 'short_text', 0, NULL, 9
FROM forms f WHERE f.slug='ciSvxgKPQVoaIF'
  AND NOT EXISTS (SELECT 1 FROM form_fields ff WHERE ff.form_id=f.id AND ff.label='Ceremony start time');
INSERT INTO form_fields (form_id, label, ftype, required, options, sort_order)
SELECT f.id, 'Reception location & address', 'short_text', 0, NULL, 10
FROM forms f WHERE f.slug='ciSvxgKPQVoaIF'
  AND NOT EXISTS (SELECT 1 FROM form_fields ff WHERE ff.form_id=f.id AND ff.label='Reception location & address');
INSERT INTO form_fields (form_id, label, ftype, required, options, sort_order)
SELECT f.id, 'Reception start time', 'short_text', 0, NULL, 11
FROM forms f WHERE f.slug='ciSvxgKPQVoaIF'
  AND NOT EXISTS (SELECT 1 FROM form_fields ff WHERE ff.form_id=f.id AND ff.label='Reception start time');
INSERT INTO form_fields (form_id, label, ftype, required, options, sort_order)
SELECT f.id, 'Approximate guest count', 'short_text', 0, NULL, 12
FROM forms f WHERE f.slug='ciSvxgKPQVoaIF'
  AND NOT EXISTS (SELECT 1 FROM form_fields ff WHERE ff.form_id=f.id AND ff.label='Approximate guest count');
INSERT INTO form_fields (form_id, label, ftype, required, options, sort_order)
SELECT f.id, 'Parents'' full names (both partners)', 'long_text', 0, NULL, 13
FROM forms f WHERE f.slug='ciSvxgKPQVoaIF'
  AND NOT EXISTS (SELECT 1 FROM form_fields ff WHERE ff.form_id=f.id AND ff.label='Parents'' full names (both partners)');
INSERT INTO form_fields (form_id, label, ftype, required, options, sort_order)
SELECT f.id, 'Immediate family members'' full names', 'long_text', 0, NULL, 14
FROM forms f WHERE f.slug='ciSvxgKPQVoaIF'
  AND NOT EXISTS (SELECT 1 FROM form_fields ff WHERE ff.form_id=f.id AND ff.label='Immediate family members'' full names');
INSERT INTO form_fields (form_id, label, ftype, required, options, sort_order)
SELECT f.id, 'Additional family photo groupings (list each group + names)', 'long_text', 0, NULL, 15
FROM forms f WHERE f.slug='ciSvxgKPQVoaIF'
  AND NOT EXISTS (SELECT 1 FROM form_fields ff WHERE ff.form_id=f.id AND ff.label='Additional family photo groupings (list each group + names)');
INSERT INTO form_fields (form_id, label, ftype, required, options, sort_order)
SELECT f.id, 'Special guests you''d like a photo with', 'long_text', 0, NULL, 16
FROM forms f WHERE f.slug='ciSvxgKPQVoaIF'
  AND NOT EXISTS (SELECT 1 FROM form_fields ff WHERE ff.form_id=f.id AND ff.label='Special guests you''d like a photo with');
INSERT INTO form_fields (form_id, label, ftype, required, options, sort_order)
SELECT f.id, 'Any sensitive family situations I should be aware of?', 'long_text', 0, NULL, 17
FROM forms f WHERE f.slug='ciSvxgKPQVoaIF'
  AND NOT EXISTS (SELECT 1 FROM form_fields ff WHERE ff.form_id=f.id AND ff.label='Any sensitive family situations I should be aware of?');
INSERT INTO form_fields (form_id, label, ftype, required, options, sort_order)
SELECT f.id, 'Where will each of you get ready? (name + address)', 'long_text', 0, NULL, 18
FROM forms f WHERE f.slug='ciSvxgKPQVoaIF'
  AND NOT EXISTS (SELECT 1 FROM form_fields ff WHERE ff.form_id=f.id AND ff.label='Where will each of you get ready? (name + address)');
INSERT INTO form_fields (form_id, label, ftype, required, options, sort_order)
SELECT f.id, 'Will you have a first look? If so, where?', 'long_text', 0, NULL, 19
FROM forms f WHERE f.slug='ciSvxgKPQVoaIF'
  AND NOT EXISTS (SELECT 1 FROM form_fields ff WHERE ff.form_id=f.id AND ff.label='Will you have a first look? If so, where?');
INSERT INTO form_fields (form_id, label, ftype, required, options, sort_order)
SELECT f.id, 'Would you like family photos before the ceremony? Wedding party too?', 'long_text', 0, NULL, 20
FROM forms f WHERE f.slug='ciSvxgKPQVoaIF'
  AND NOT EXISTS (SELECT 1 FROM form_fields ff WHERE ff.form_id=f.id AND ff.label='Would you like family photos before the ceremony? Wedding party too?');
INSERT INTO form_fields (form_id, label, ftype, required, options, sort_order)
SELECT f.id, 'Wedding party members (names + roles)', 'long_text', 0, NULL, 21
FROM forms f WHERE f.slug='ciSvxgKPQVoaIF'
  AND NOT EXISTS (SELECT 1 FROM form_fields ff WHERE ff.form_id=f.id AND ff.label='Wedding party members (names + roles)');
INSERT INTO form_fields (form_id, label, ftype, required, options, sort_order)
SELECT f.id, 'Any rituals or traditions during the ceremony?', 'long_text', 0, NULL, 22
FROM forms f WHERE f.slug='ciSvxgKPQVoaIF'
  AND NOT EXISTS (SELECT 1 FROM form_fields ff WHERE ff.form_id=f.id AND ff.label='Any rituals or traditions during the ceremony?');
INSERT INTO form_fields (form_id, label, ftype, required, options, sort_order)
SELECT f.id, 'Any unique or special touches I should be aware of?', 'long_text', 0, NULL, 23
FROM forms f WHERE f.slug='ciSvxgKPQVoaIF'
  AND NOT EXISTS (SELECT 1 FROM form_fields ff WHERE ff.form_id=f.id AND ff.label='Any unique or special touches I should be aware of?');
INSERT INTO form_fields (form_id, label, ftype, required, options, sort_order)
SELECT f.id, 'Specific locations on site you''d love me to shoot?', 'long_text', 0, NULL, 24
FROM forms f WHERE f.slug='ciSvxgKPQVoaIF'
  AND NOT EXISTS (SELECT 1 FROM form_fields ff WHERE ff.form_id=f.id AND ff.label='Specific locations on site you''d love me to shoot?');
INSERT INTO form_fields (form_id, label, ftype, required, options, sort_order)
SELECT f.id, 'Will there be a cocktail hour? When?', 'short_text', 0, NULL, 25
FROM forms f WHERE f.slug='ciSvxgKPQVoaIF'
  AND NOT EXISTS (SELECT 1 FROM form_fields ff WHERE ff.form_id=f.id AND ff.label='Will there be a cocktail hour? When?');
INSERT INTO form_fields (form_id, label, ftype, required, options, sort_order)
SELECT f.id, 'Music plans (DJ, live band, playlist, etc.)', 'short_text', 0, NULL, 26
FROM forms f WHERE f.slug='ciSvxgKPQVoaIF'
  AND NOT EXISTS (SELECT 1 FROM form_fields ff WHERE ff.form_id=f.id AND ff.label='Music plans (DJ, live band, playlist, etc.)');
INSERT INTO form_fields (form_id, label, ftype, required, options, sort_order)
SELECT f.id, 'Will you have a first dance?', 'yesno', 0, NULL, 27
FROM forms f WHERE f.slug='ciSvxgKPQVoaIF'
  AND NOT EXISTS (SELECT 1 FROM form_fields ff WHERE ff.form_id=f.id AND ff.label='Will you have a first dance?');
INSERT INTO form_fields (form_id, label, ftype, required, options, sort_order)
SELECT f.id, 'Special events planned for the reception', 'long_text', 0, NULL, 28
FROM forms f WHERE f.slug='ciSvxgKPQVoaIF'
  AND NOT EXISTS (SELECT 1 FROM form_fields ff WHERE ff.form_id=f.id AND ff.label='Special events planned for the reception');
INSERT INTO form_fields (form_id, label, ftype, required, options, sort_order)
SELECT f.id, 'Vendor details — name, email & website for each (planner, caterer, florist, DJ, photo booth, videographer, cake/dessert, others)', 'long_text', 0, NULL, 29
FROM forms f WHERE f.slug='ciSvxgKPQVoaIF'
  AND NOT EXISTS (SELECT 1 FROM form_fields ff WHERE ff.form_id=f.id AND ff.label='Vendor details — name, email & website for each (planner, caterer, florist, DJ, photo booth, videographer, cake/dessert, others)');
INSERT INTO form_fields (form_id, label, ftype, required, options, sort_order)
SELECT f.id, 'Anything else you''d like me to know?', 'long_text', 0, NULL, 30
FROM forms f WHERE f.slug='ciSvxgKPQVoaIF'
  AND NOT EXISTS (SELECT 1 FROM form_fields ff WHERE ff.form_id=f.id AND ff.label='Anything else you''d like me to know?');
INSERT INTO form_fields (form_id, label, ftype, required, options, sort_order)
SELECT f.id, 'Wedding hashtag(s)', 'short_text', 0, NULL, 31
FROM forms f WHERE f.slug='ciSvxgKPQVoaIF'
  AND NOT EXISTS (SELECT 1 FROM form_fields ff WHERE ff.form_id=f.id AND ff.label='Wedding hashtag(s)');
INSERT INTO form_fields (form_id, label, ftype, required, options, sort_order)
SELECT f.id, 'Instagram handles (you and your partner)', 'short_text', 0, NULL, 32
FROM forms f WHERE f.slug='ciSvxgKPQVoaIF'
  AND NOT EXISTS (SELECT 1 FROM form_fields ff WHERE ff.form_id=f.id AND ff.label='Instagram handles (you and your partner)');

INSERT INTO forms (slug, title, kind, intro, active)
SELECT 'VVvJGHCsEdrljO', 'New Client History Questionnaire', 'questionnaire', 'This questionnaire covers everything I need to know to get started and book your discovery call. Please fill it out as thoroughly as you can.', 1
WHERE NOT EXISTS (SELECT 1 FROM forms WHERE title='New Client History Questionnaire');
INSERT INTO form_fields (form_id, label, ftype, required, options, sort_order)
SELECT f.id, 'Company name', 'short_text', 1, NULL, 1
FROM forms f WHERE f.slug='VVvJGHCsEdrljO'
  AND NOT EXISTS (SELECT 1 FROM form_fields ff WHERE ff.form_id=f.id AND ff.label='Company name');
INSERT INTO form_fields (form_id, label, ftype, required, options, sort_order)
SELECT f.id, 'Primary contact name', 'short_text', 1, NULL, 2
FROM forms f WHERE f.slug='VVvJGHCsEdrljO'
  AND NOT EXISTS (SELECT 1 FROM form_fields ff WHERE ff.form_id=f.id AND ff.label='Primary contact name');
INSERT INTO form_fields (form_id, label, ftype, required, options, sort_order)
SELECT f.id, 'Primary contact email', 'email', 1, NULL, 3
FROM forms f WHERE f.slug='VVvJGHCsEdrljO'
  AND NOT EXISTS (SELECT 1 FROM form_fields ff WHERE ff.form_id=f.id AND ff.label='Primary contact email');
INSERT INTO form_fields (form_id, label, ftype, required, options, sort_order)
SELECT f.id, 'Secondary contact name', 'short_text', 0, NULL, 4
FROM forms f WHERE f.slug='VVvJGHCsEdrljO'
  AND NOT EXISTS (SELECT 1 FROM form_fields ff WHERE ff.form_id=f.id AND ff.label='Secondary contact name');
INSERT INTO form_fields (form_id, label, ftype, required, options, sort_order)
SELECT f.id, 'Secondary contact email', 'email', 0, NULL, 5
FROM forms f WHERE f.slug='VVvJGHCsEdrljO'
  AND NOT EXISTS (SELECT 1 FROM form_fields ff WHERE ff.form_id=f.id AND ff.label='Secondary contact email');
INSERT INTO form_fields (form_id, label, ftype, required, options, sort_order)
SELECT f.id, 'Company phone number', 'short_text', 0, NULL, 6
FROM forms f WHERE f.slug='VVvJGHCsEdrljO'
  AND NOT EXISTS (SELECT 1 FROM form_fields ff WHERE ff.form_id=f.id AND ff.label='Company phone number');
INSERT INTO form_fields (form_id, label, ftype, required, options, sort_order)
SELECT f.id, 'Website and/or social media handle', 'short_text', 0, NULL, 7
FROM forms f WHERE f.slug='VVvJGHCsEdrljO'
  AND NOT EXISTS (SELECT 1 FROM form_fields ff WHERE ff.form_id=f.id AND ff.label='Website and/or social media handle');
INSERT INTO form_fields (form_id, label, ftype, required, options, sort_order)
SELECT f.id, 'Business or event address', 'short_text', 0, NULL, 8
FROM forms f WHERE f.slug='VVvJGHCsEdrljO'
  AND NOT EXISTS (SELECT 1 FROM form_fields ff WHERE ff.form_id=f.id AND ff.label='Business or event address');
INSERT INTO form_fields (form_id, label, ftype, required, options, sort_order)
SELECT f.id, 'How did you hear about us?', 'dropdown', 0, '["Referral", "Instagram", "Google search", "Returning client", "Other"]', 9
FROM forms f WHERE f.slug='VVvJGHCsEdrljO'
  AND NOT EXISTS (SELECT 1 FROM form_fields ff WHERE ff.form_id=f.id AND ff.label='How did you hear about us?');
INSERT INTO form_fields (form_id, label, ftype, required, options, sort_order)
SELECT f.id, 'Tell me a bit about your business and its story', 'long_text', 0, NULL, 10
FROM forms f WHERE f.slug='VVvJGHCsEdrljO'
  AND NOT EXISTS (SELECT 1 FROM form_fields ff WHERE ff.form_id=f.id AND ff.label='Tell me a bit about your business and its story');
INSERT INTO form_fields (form_id, label, ftype, required, options, sort_order)
SELECT f.id, 'What do you need photography for? (e.g. menu, social, website, PR, branding)', 'long_text', 0, NULL, 11
FROM forms f WHERE f.slug='VVvJGHCsEdrljO'
  AND NOT EXISTS (SELECT 1 FROM form_fields ff WHERE ff.form_id=f.id AND ff.label='What do you need photography for? (e.g. menu, social, website, PR, branding)');
INSERT INTO form_fields (form_id, label, ftype, required, options, sort_order)
SELECT f.id, 'What have your past experiences with photographers been like?', 'long_text', 0, NULL, 12
FROM forms f WHERE f.slug='VVvJGHCsEdrljO'
  AND NOT EXISTS (SELECT 1 FROM form_fields ff WHERE ff.form_id=f.id AND ff.label='What have your past experiences with photographers been like?');
INSERT INTO form_fields (form_id, label, ftype, required, options, sort_order)
SELECT f.id, 'Which best describes where you are right now?', 'dropdown', 0, '["Just exploring", "Planning a specific shoot", "Ready to book", "Ongoing / retainer needs"]', 13
FROM forms f WHERE f.slug='VVvJGHCsEdrljO'
  AND NOT EXISTS (SELECT 1 FROM form_fields ff WHERE ff.form_id=f.id AND ff.label='Which best describes where you are right now?');
INSERT INTO form_fields (form_id, label, ftype, required, options, sort_order)
SELECT f.id, 'What are your goals for this project?', 'long_text', 0, NULL, 14
FROM forms f WHERE f.slug='VVvJGHCsEdrljO'
  AND NOT EXISTS (SELECT 1 FROM form_fields ff WHERE ff.form_id=f.id AND ff.label='What are your goals for this project?');
INSERT INTO form_fields (form_id, label, ftype, required, options, sort_order)
SELECT f.id, 'Any inspiration, references, or brands whose look you love?', 'long_text', 0, NULL, 15
FROM forms f WHERE f.slug='VVvJGHCsEdrljO'
  AND NOT EXISTS (SELECT 1 FROM form_fields ff WHERE ff.form_id=f.id AND ff.label='Any inspiration, references, or brands whose look you love?');

INSERT INTO forms (slug, title, kind, intro, active)
SELECT 'GZGCNSuABjKiMr', 'Experience Questionnaire', 'questionnaire', 'It''s been such a pleasure working together. Please take a moment to let me know how the experience felt for you. I welcome constructive criticism as much as positive feedback.', 1
WHERE NOT EXISTS (SELECT 1 FROM forms WHERE title='Experience Questionnaire');
INSERT INTO form_fields (form_id, label, ftype, required, options, sort_order)
SELECT f.id, 'What was the primary service we worked on together?', 'short_text', 1, NULL, 1
FROM forms f WHERE f.slug='GZGCNSuABjKiMr'
  AND NOT EXISTS (SELECT 1 FROM form_fields ff WHERE ff.form_id=f.id AND ff.label='What was the primary service we worked on together?');
INSERT INTO form_fields (form_id, label, ftype, required, options, sort_order)
SELECT f.id, 'How satisfied are you with your overall experience?', 'dropdown', 0, '["Extremely satisfied", "Satisfied", "Neutral", "Unsatisfied"]', 2
FROM forms f WHERE f.slug='GZGCNSuABjKiMr'
  AND NOT EXISTS (SELECT 1 FROM form_fields ff WHERE ff.form_id=f.id AND ff.label='How satisfied are you with your overall experience?');
INSERT INTO form_fields (form_id, label, ftype, required, options, sort_order)
SELECT f.id, 'What parts of your experience did you enjoy most?', 'long_text', 0, NULL, 3
FROM forms f WHERE f.slug='GZGCNSuABjKiMr'
  AND NOT EXISTS (SELECT 1 FROM form_fields ff WHERE ff.form_id=f.id AND ff.label='What parts of your experience did you enjoy most?');
INSERT INTO form_fields (form_id, label, ftype, required, options, sort_order)
SELECT f.id, 'Where could I improve?', 'long_text', 0, NULL, 4
FROM forms f WHERE f.slug='GZGCNSuABjKiMr'
  AND NOT EXISTS (SELECT 1 FROM form_fields ff WHERE ff.form_id=f.id AND ff.label='Where could I improve?');
INSERT INTO form_fields (form_id, label, ftype, required, options, sort_order)
SELECT f.id, 'What led you to book with me over another business?', 'long_text', 0, NULL, 5
FROM forms f WHERE f.slug='GZGCNSuABjKiMr'
  AND NOT EXISTS (SELECT 1 FROM form_fields ff WHERE ff.form_id=f.id AND ff.label='What led you to book with me over another business?');
INSERT INTO form_fields (form_id, label, ftype, required, options, sort_order)
SELECT f.id, 'Would you recommend my services?', 'yesno', 0, NULL, 6
FROM forms f WHERE f.slug='GZGCNSuABjKiMr'
  AND NOT EXISTS (SELECT 1 FROM form_fields ff WHERE ff.form_id=f.id AND ff.label='Would you recommend my services?');
INSERT INTO form_fields (form_id, label, ftype, required, options, sort_order)
SELECT f.id, 'Why or why not?', 'long_text', 0, NULL, 7
FROM forms f WHERE f.slug='GZGCNSuABjKiMr'
  AND NOT EXISTS (SELECT 1 FROM form_fields ff WHERE ff.form_id=f.id AND ff.label='Why or why not?');
INSERT INTO form_fields (form_id, label, ftype, required, options, sort_order)
SELECT f.id, 'Please share your candid review here', 'long_text', 0, NULL, 8
FROM forms f WHERE f.slug='GZGCNSuABjKiMr'
  AND NOT EXISTS (SELECT 1 FROM form_fields ff WHERE ff.form_id=f.id AND ff.label='Please share your candid review here');
INSERT INTO form_fields (form_id, label, ftype, required, options, sort_order)
SELECT f.id, 'Do I have permission to share your testimonial online?', 'yesno', 0, NULL, 9
FROM forms f WHERE f.slug='GZGCNSuABjKiMr'
  AND NOT EXISTS (SELECT 1 FROM form_fields ff WHERE ff.form_id=f.id AND ff.label='Do I have permission to share your testimonial online?');
INSERT INTO form_fields (form_id, label, ftype, required, options, sort_order)
SELECT f.id, 'Would you like to stay in touch?', 'yesno', 1, NULL, 10
FROM forms f WHERE f.slug='GZGCNSuABjKiMr'
  AND NOT EXISTS (SELECT 1 FROM form_fields ff WHERE ff.form_id=f.id AND ff.label='Would you like to stay in touch?');
INSERT INTO form_fields (form_id, label, ftype, required, options, sort_order)
SELECT f.id, 'If so, what''s the best email going forward?', 'email', 0, NULL, 11
FROM forms f WHERE f.slug='GZGCNSuABjKiMr'
  AND NOT EXISTS (SELECT 1 FROM form_fields ff WHERE ff.form_id=f.id AND ff.label='If so, what''s the best email going forward?');
INSERT INTO form_fields (form_id, label, ftype, required, options, sort_order)
SELECT f.id, 'Your Instagram handle', 'short_text', 0, NULL, 12
FROM forms f WHERE f.slug='GZGCNSuABjKiMr'
  AND NOT EXISTS (SELECT 1 FROM form_fields ff WHERE ff.form_id=f.id AND ff.label='Your Instagram handle');

INSERT INTO forms (slug, title, kind, intro, active)
SELECT '80h9utBLMMj691', 'Satisfaction Questionnaire', 'questionnaire', 'It''s been such a pleasure working with you. Please take a moment to fill out the feedback below. I welcome constructive criticism and suggestions as much as positive feedback — feel free to be candid.', 1
WHERE NOT EXISTS (SELECT 1 FROM forms WHERE title='Satisfaction Questionnaire');
INSERT INTO form_fields (form_id, label, ftype, required, options, sort_order)
SELECT f.id, 'Name', 'short_text', 1, NULL, 1
FROM forms f WHERE f.slug='80h9utBLMMj691'
  AND NOT EXISTS (SELECT 1 FROM form_fields ff WHERE ff.form_id=f.id AND ff.label='Name');
INSERT INTO form_fields (form_id, label, ftype, required, options, sort_order)
SELECT f.id, 'Email address', 'email', 1, NULL, 2
FROM forms f WHERE f.slug='80h9utBLMMj691'
  AND NOT EXISTS (SELECT 1 FROM form_fields ff WHERE ff.form_id=f.id AND ff.label='Email address');
INSERT INTO form_fields (form_id, label, ftype, required, options, sort_order)
SELECT f.id, 'Phone number', 'short_text', 1, NULL, 3
FROM forms f WHERE f.slug='80h9utBLMMj691'
  AND NOT EXISTS (SELECT 1 FROM form_fields ff WHERE ff.form_id=f.id AND ff.label='Phone number');
INSERT INTO form_fields (form_id, label, ftype, required, options, sort_order)
SELECT f.id, 'Instagram handle', 'short_text', 0, NULL, 4
FROM forms f WHERE f.slug='80h9utBLMMj691'
  AND NOT EXISTS (SELECT 1 FROM form_fields ff WHERE ff.form_id=f.id AND ff.label='Instagram handle');
INSERT INTO form_fields (form_id, label, ftype, required, options, sort_order)
SELECT f.id, 'What did we work on together?', 'short_text', 1, NULL, 5
FROM forms f WHERE f.slug='80h9utBLMMj691'
  AND NOT EXISTS (SELECT 1 FROM form_fields ff WHERE ff.form_id=f.id AND ff.label='What did we work on together?');
INSERT INTO form_fields (form_id, label, ftype, required, options, sort_order)
SELECT f.id, 'How did you hear about us?', 'short_text', 0, NULL, 6
FROM forms f WHERE f.slug='80h9utBLMMj691'
  AND NOT EXISTS (SELECT 1 FROM form_fields ff WHERE ff.form_id=f.id AND ff.label='How did you hear about us?');
INSERT INTO form_fields (form_id, label, ftype, required, options, sort_order)
SELECT f.id, 'What led you to book with us over another business?', 'long_text', 0, NULL, 7
FROM forms f WHERE f.slug='80h9utBLMMj691'
  AND NOT EXISTS (SELECT 1 FROM form_fields ff WHERE ff.form_id=f.id AND ff.label='What led you to book with us over another business?');
INSERT INTO form_fields (form_id, label, ftype, required, options, sort_order)
SELECT f.id, 'How satisfied are you with your overall experience?', 'dropdown', 0, '["Extremely satisfied", "Satisfied", "Neutral", "Unsatisfied"]', 8
FROM forms f WHERE f.slug='80h9utBLMMj691'
  AND NOT EXISTS (SELECT 1 FROM form_fields ff WHERE ff.form_id=f.id AND ff.label='How satisfied are you with your overall experience?');
INSERT INTO form_fields (form_id, label, ftype, required, options, sort_order)
SELECT f.id, 'What parts of your experience did you enjoy?', 'long_text', 0, NULL, 9
FROM forms f WHERE f.slug='80h9utBLMMj691'
  AND NOT EXISTS (SELECT 1 FROM form_fields ff WHERE ff.form_id=f.id AND ff.label='What parts of your experience did you enjoy?');
INSERT INTO form_fields (form_id, label, ftype, required, options, sort_order)
SELECT f.id, 'Where could we improve?', 'long_text', 0, NULL, 10
FROM forms f WHERE f.slug='80h9utBLMMj691'
  AND NOT EXISTS (SELECT 1 FROM form_fields ff WHERE ff.form_id=f.id AND ff.label='Where could we improve?');
INSERT INTO form_fields (form_id, label, ftype, required, options, sort_order)
SELECT f.id, 'Please share your candid review here', 'long_text', 0, NULL, 11
FROM forms f WHERE f.slug='80h9utBLMMj691'
  AND NOT EXISTS (SELECT 1 FROM form_fields ff WHERE ff.form_id=f.id AND ff.label='Please share your candid review here');
INSERT INTO form_fields (form_id, label, ftype, required, options, sort_order)
SELECT f.id, 'Do we have permission to share your testimonial online?', 'yesno', 0, NULL, 12
FROM forms f WHERE f.slug='80h9utBLMMj691'
  AND NOT EXISTS (SELECT 1 FROM form_fields ff WHERE ff.form_id=f.id AND ff.label='Do we have permission to share your testimonial online?');
INSERT INTO form_fields (form_id, label, ftype, required, options, sort_order)
SELECT f.id, 'Would you like to stay in touch?', 'yesno', 0, NULL, 13
FROM forms f WHERE f.slug='80h9utBLMMj691'
  AND NOT EXISTS (SELECT 1 FROM form_fields ff WHERE ff.form_id=f.id AND ff.label='Would you like to stay in touch?');
INSERT INTO form_fields (form_id, label, ftype, required, options, sort_order)
SELECT f.id, 'Would you recommend our services?', 'yesno', 0, NULL, 14
FROM forms f WHERE f.slug='80h9utBLMMj691'
  AND NOT EXISTS (SELECT 1 FROM form_fields ff WHERE ff.form_id=f.id AND ff.label='Would you recommend our services?');
INSERT INTO form_fields (form_id, label, ftype, required, options, sort_order)
SELECT f.id, 'Why or why not?', 'long_text', 0, NULL, 15
FROM forms f WHERE f.slug='80h9utBLMMj691'
  AND NOT EXISTS (SELECT 1 FROM form_fields ff WHERE ff.form_id=f.id AND ff.label='Why or why not?');

