-- 043_seed_my_templates_questionnaires.sql
-- 2 questionnaires from the 'My Templates' batch (testimonial request,
-- client onboarding). Adapted for F&B/commercial. Idempotent. Generated by
-- gen_seed_043.py. The builder has no multi-select ftype, so 'select all
-- that apply' items are captured as long_text (noted for a future ftype).

INSERT INTO forms (slug, title, kind, intro, active)
SELECT 'TVLhGQXWZZP6F6', 'Request for a Testimonial', 'questionnaire', 'I''d love to hear how the project went. A few quick questions — with your approval, your words may appear (first name + last initial only) on my website and marketing.', 1
WHERE NOT EXISTS (SELECT 1 FROM forms WHERE title='Request for a Testimonial');
INSERT INTO form_fields (form_id, label, ftype, required, options, sort_order)
SELECT f.id, 'How likely are you to recommend my work to a colleague?', 'dropdown', 1, '["Extremely likely", "Very likely", "Somewhat likely", "Not likely"]', 1
FROM forms f WHERE f.slug='TVLhGQXWZZP6F6'
  AND NOT EXISTS (SELECT 1 FROM form_fields ff WHERE ff.form_id=f.id AND ff.label='How likely are you to recommend my work to a colleague?');
INSERT INTO form_fields (form_id, label, ftype, required, options, sort_order)
SELECT f.id, 'In a few words, what was it like working together?', 'long_text', 1, NULL, 2
FROM forms f WHERE f.slug='TVLhGQXWZZP6F6'
  AND NOT EXISTS (SELECT 1 FROM form_fields ff WHERE ff.form_id=f.id AND ff.label='In a few words, what was it like working together?');
INSERT INTO form_fields (form_id, label, ftype, required, options, sort_order)
SELECT f.id, 'What stood out most about the final images or the process?', 'long_text', 0, NULL, 3
FROM forms f WHERE f.slug='TVLhGQXWZZP6F6'
  AND NOT EXISTS (SELECT 1 FROM form_fields ff WHERE ff.form_id=f.id AND ff.label='What stood out most about the final images or the process?');
INSERT INTO form_fields (form_id, label, ftype, required, options, sort_order)
SELECT f.id, 'May I feature your testimonial — first name + last initial — on my website and marketing?', 'yesno', 1, NULL, 4
FROM forms f WHERE f.slug='TVLhGQXWZZP6F6'
  AND NOT EXISTS (SELECT 1 FROM form_fields ff WHERE ff.form_id=f.id AND ff.label='May I feature your testimonial — first name + last initial — on my website and marketing?');
INSERT INTO form_fields (form_id, label, ftype, required, options, sort_order)
SELECT f.id, 'Your name and business (for crediting)', 'short_text', 0, NULL, 5
FROM forms f WHERE f.slug='TVLhGQXWZZP6F6'
  AND NOT EXISTS (SELECT 1 FROM form_fields ff WHERE ff.form_id=f.id AND ff.label='Your name and business (for crediting)');
INSERT INTO forms (slug, title, kind, intro, active)
SELECT 'JKTkoJ3L367dug', 'Client Onboarding Questionnaire', 'questionnaire', 'Welcome aboard. A few details so I can tailor the shoot and deliverables to your brand. Fill in as much as you can — more is always better than less.', 1
WHERE NOT EXISTS (SELECT 1 FROM forms WHERE title='Client Onboarding Questionnaire');
INSERT INTO form_fields (form_id, label, ftype, required, options, sort_order)
SELECT f.id, 'Primary contact — full name', 'short_text', 1, NULL, 1
FROM forms f WHERE f.slug='JKTkoJ3L367dug'
  AND NOT EXISTS (SELECT 1 FROM form_fields ff WHERE ff.form_id=f.id AND ff.label='Primary contact — full name');
INSERT INTO form_fields (form_id, label, ftype, required, options, sort_order)
SELECT f.id, 'Primary contact — email', 'email', 1, NULL, 2
FROM forms f WHERE f.slug='JKTkoJ3L367dug'
  AND NOT EXISTS (SELECT 1 FROM form_fields ff WHERE ff.form_id=f.id AND ff.label='Primary contact — email');
INSERT INTO form_fields (form_id, label, ftype, required, options, sort_order)
SELECT f.id, 'Business / brand name', 'short_text', 1, NULL, 3
FROM forms f WHERE f.slug='JKTkoJ3L367dug'
  AND NOT EXISTS (SELECT 1 FROM form_fields ff WHERE ff.form_id=f.id AND ff.label='Business / brand name');
INSERT INTO form_fields (form_id, label, ftype, required, options, sort_order)
SELECT f.id, 'Secondary contact — full name', 'short_text', 0, NULL, 4
FROM forms f WHERE f.slug='JKTkoJ3L367dug'
  AND NOT EXISTS (SELECT 1 FROM form_fields ff WHERE ff.form_id=f.id AND ff.label='Secondary contact — full name');
INSERT INTO form_fields (form_id, label, ftype, required, options, sort_order)
SELECT f.id, 'Secondary contact — email', 'email', 0, NULL, 5
FROM forms f WHERE f.slug='JKTkoJ3L367dug'
  AND NOT EXISTS (SELECT 1 FROM form_fields ff WHERE ff.form_id=f.id AND ff.label='Secondary contact — email');
INSERT INTO form_fields (form_id, label, ftype, required, options, sort_order)
SELECT f.id, 'Secondary contact — role / title', 'short_text', 0, NULL, 6
FROM forms f WHERE f.slug='JKTkoJ3L367dug'
  AND NOT EXISTS (SELECT 1 FROM form_fields ff WHERE ff.form_id=f.id AND ff.label='Secondary contact — role / title');
INSERT INTO form_fields (form_id, label, ftype, required, options, sort_order)
SELECT f.id, 'Preferred contact method', 'dropdown', 1, '["Email", "Phone call", "Text"]', 7
FROM forms f WHERE f.slug='JKTkoJ3L367dug'
  AND NOT EXISTS (SELECT 1 FROM form_fields ff WHERE ff.form_id=f.id AND ff.label='Preferred contact method');
INSERT INTO form_fields (form_id, label, ftype, required, options, sort_order)
SELECT f.id, 'Best times to reach you (e.g. weekday mornings, weekend afternoons)', 'long_text', 0, NULL, 8
FROM forms f WHERE f.slug='JKTkoJ3L367dug'
  AND NOT EXISTS (SELECT 1 FROM form_fields ff WHERE ff.form_id=f.id AND ff.label='Best times to reach you (e.g. weekday mornings, weekend afternoons)');
INSERT INTO form_fields (form_id, label, ftype, required, options, sort_order)
SELECT f.id, 'What are your biggest content or visual challenges right now?', 'long_text', 1, NULL, 9
FROM forms f WHERE f.slug='JKTkoJ3L367dug'
  AND NOT EXISTS (SELECT 1 FROM form_fields ff WHERE ff.form_id=f.id AND ff.label='What are your biggest content or visual challenges right now?');
INSERT INTO form_fields (form_id, label, ftype, required, options, sort_order)
SELECT f.id, 'Anything else I should know — links, brand guidelines, references?', 'long_text', 0, NULL, 10
FROM forms f WHERE f.slug='JKTkoJ3L367dug'
  AND NOT EXISTS (SELECT 1 FROM form_fields ff WHERE ff.form_id=f.id AND ff.label='Anything else I should know — links, brand guidelines, references?');
